// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"
	"database/sql"
)

const createJobOffer = `-- name: CreateJobOffer :one
INSERT INTO job_offers (
    id, title, company, location, description, url, source, published_at, skills,
    salary_employment, salary_b2b, salary_contract
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, company, location, description, url, source, published_at, skills, created_at, last_seen_at, salary_employment, salary_b2b, salary_contract
`

type CreateJobOfferParams struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	Company          sql.NullString `json:"company"`
	Location         sql.NullString `json:"location"`
	Description      sql.NullString `json:"description"`
	Url              string         `json:"url"`
	Source           string         `json:"source"`
	PublishedAt      sql.NullTime   `json:"published_at"`
	Skills           sql.NullString `json:"skills"`
	SalaryEmployment sql.NullString `json:"salary_employment"`
	SalaryB2b        sql.NullString `json:"salary_b2b"`
	SalaryContract   sql.NullString `json:"salary_contract"`
}

func (q *Queries) CreateJobOffer(ctx context.Context, arg CreateJobOfferParams) (JobOffer, error) {
	row := q.db.QueryRowContext(ctx, createJobOffer,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Description,
		arg.Url,
		arg.Source,
		arg.PublishedAt,
		arg.Skills,
		arg.SalaryEmployment,
		arg.SalaryB2b,
		arg.SalaryContract,
	)
	var i JobOffer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Description,
		&i.Url,
		&i.Source,
		&i.PublishedAt,
		&i.Skills,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SalaryEmployment,
		&i.SalaryB2b,
		&i.SalaryContract,
	)
	return i, err
}

const deleteJobOffer = `-- name: DeleteJobOffer :exec
DELETE FROM job_offers WHERE id = ?
`

func (q *Queries) DeleteJobOffer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJobOffer, id)
	return err
}

const listJobOffers = `-- name: ListJobOffers :many
SELECT id, title, company, location, description, url, source, published_at, skills, created_at, last_seen_at, salary_employment, salary_b2b, salary_contract FROM job_offers 
ORDER BY created_at DESC 
LIMIT ? OFFSET ?
`

type ListJobOffersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListJobOffers(ctx context.Context, arg ListJobOffersParams) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listJobOffers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.SalaryEmployment,
			&i.SalaryB2b,
			&i.SalaryContract,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOffersByCompany = `-- name: ListJobOffersByCompany :many
SELECT id, title, company, location, description, url, source, published_at, skills, created_at, last_seen_at, salary_employment, salary_b2b, salary_contract FROM job_offers 
WHERE company = ?
ORDER BY published_at DESC
`

func (q *Queries) ListJobOffersByCompany(ctx context.Context, company sql.NullString) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listJobOffersByCompany, company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.SalaryEmployment,
			&i.SalaryB2b,
			&i.SalaryContract,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOffersByLocation = `-- name: ListJobOffersByLocation :many
SELECT id, title, company, location, description, url, source, published_at, skills, created_at, last_seen_at, salary_employment, salary_b2b, salary_contract FROM job_offers 
WHERE location LIKE ?
ORDER BY published_at DESC
`

func (q *Queries) ListJobOffersByLocation(ctx context.Context, location sql.NullString) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listJobOffersByLocation, location)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.SalaryEmployment,
			&i.SalaryB2b,
			&i.SalaryContract,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOffersBySource = `-- name: ListJobOffersBySource :many
SELECT id, title, company, location, description, url, source, published_at, skills, created_at, last_seen_at, salary_employment, salary_b2b, salary_contract FROM job_offers 
WHERE source = ?
ORDER BY published_at DESC 
LIMIT ? OFFSET ?
`

type ListJobOffersBySourceParams struct {
	Source string `json:"source"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListJobOffersBySource(ctx context.Context, arg ListJobOffersBySourceParams) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listJobOffersBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.SalaryEmployment,
			&i.SalaryB2b,
			&i.SalaryContract,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentJobOffers = `-- name: ListRecentJobOffers :many
SELECT id, title, company, location, description, url, source, published_at, skills, created_at, last_seen_at, salary_employment, salary_b2b, salary_contract FROM job_offers 
ORDER BY published_at DESC 
LIMIT ?
`

func (q *Queries) ListRecentJobOffers(ctx context.Context, limit int64) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listRecentJobOffers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.SalaryEmployment,
			&i.SalaryB2b,
			&i.SalaryContract,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobOffer = `-- name: UpdateJobOffer :one
UPDATE job_offers
SET 
    title = ?,
    company = ?,
    location = ?,
    description = ?,
    published_at = ?,
    skills = ?,
    salary_employment = ?,
    salary_b2b = ?,
    salary_contract = ?,
    last_seen_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, company, location, description, url, source, published_at, skills, created_at, last_seen_at, salary_employment, salary_b2b, salary_contract
`

type UpdateJobOfferParams struct {
	Title            string         `json:"title"`
	Company          sql.NullString `json:"company"`
	Location         sql.NullString `json:"location"`
	Description      sql.NullString `json:"description"`
	PublishedAt      sql.NullTime   `json:"published_at"`
	Skills           sql.NullString `json:"skills"`
	SalaryEmployment sql.NullString `json:"salary_employment"`
	SalaryB2b        sql.NullString `json:"salary_b2b"`
	SalaryContract   sql.NullString `json:"salary_contract"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateJobOffer(ctx context.Context, arg UpdateJobOfferParams) (JobOffer, error) {
	row := q.db.QueryRowContext(ctx, updateJobOffer,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Description,
		arg.PublishedAt,
		arg.Skills,
		arg.SalaryEmployment,
		arg.SalaryB2b,
		arg.SalaryContract,
		arg.ID,
	)
	var i JobOffer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Description,
		&i.Url,
		&i.Source,
		&i.PublishedAt,
		&i.Skills,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SalaryEmployment,
		&i.SalaryB2b,
		&i.SalaryContract,
	)
	return i, err
}

const upsertJobOffer = `-- name: UpsertJobOffer :one
INSERT INTO job_offers (
    id, title, company, location, description, url, source, published_at, skills,
    salary_employment, salary_b2b, salary_contract
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(url) DO UPDATE SET
    title = excluded.title,
    company = excluded.company,
    location = excluded.location,
    description = excluded.description,
    published_at = excluded.published_at,
    skills = excluded.skills,
    salary_employment = excluded.salary_employment,
    salary_b2b = excluded.salary_b2b,
    salary_contract = excluded.salary_contract,
    last_seen_at = CURRENT_TIMESTAMP
RETURNING id, title, company, location, description, url, source, published_at, skills, created_at, last_seen_at, salary_employment, salary_b2b, salary_contract
`

type UpsertJobOfferParams struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	Company          sql.NullString `json:"company"`
	Location         sql.NullString `json:"location"`
	Description      sql.NullString `json:"description"`
	Url              string         `json:"url"`
	Source           string         `json:"source"`
	PublishedAt      sql.NullTime   `json:"published_at"`
	Skills           sql.NullString `json:"skills"`
	SalaryEmployment sql.NullString `json:"salary_employment"`
	SalaryB2b        sql.NullString `json:"salary_b2b"`
	SalaryContract   sql.NullString `json:"salary_contract"`
}

func (q *Queries) UpsertJobOffer(ctx context.Context, arg UpsertJobOfferParams) (JobOffer, error) {
	row := q.db.QueryRowContext(ctx, upsertJobOffer,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Description,
		arg.Url,
		arg.Source,
		arg.PublishedAt,
		arg.Skills,
		arg.SalaryEmployment,
		arg.SalaryB2b,
		arg.SalaryContract,
	)
	var i JobOffer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Description,
		&i.Url,
		&i.Source,
		&i.PublishedAt,
		&i.Skills,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.SalaryEmployment,
		&i.SalaryB2b,
		&i.SalaryContract,
	)
	return i, err
}
